# install packages:
## grml-zsh-config (for non-archlinux run: $ wget -O .zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc)
## powerline
## zsh 
## zsh-autosuggestions 
## zsh-completions 
## zsh-doc 
## zsh-history-substring-search 
## zsh-lovers 
## zsh-syntax-highlighting 
## zsh-theme-powerlevel10k

# create .zshrc with:
alias yay='yay --color=auto'
alias pacman='pacman --color=auto'

. /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
. /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
. /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# and run
## p10k configure  

